---
apiVersion: v1
kind: Service
metadata:
  name: demo-service
  labels:
    k8s-app: demo-app
spec:
  type: LoadBalancer
  selector:
    lb-target: web
  ports:
    - port: 80
      name: http
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: demo-app-v1
  labels:
    k8s-app: demo-app-v1
spec:
  replicas: 3
  template:
    metadata:
      labels:
        k8s-app: demo-app-v1
        lb-target: web
    spec:
      containers:
        - image: hub.c.163.com/gobyoung/elk:log-courier-latest
          name: log-courier
          volumeMounts:
            - name: log-storage
              mountPath: /var/log/nginx
        - image: hub.c.163.com/gobyoung/elk:nginx-demo
          name: nginx
          ports:
            - containerPort: 80
          volumeMounts:
            - name: log-storage
              mountPath: /var/log/nginx
            - name: www-storage
              mountPath: /usr/share/nginx/html
      volumes:
        - name: www-storage
          gitRepo:
            repository: https://github.com/tazjin/k8s-elk-demo.git
            revision: static-v1
        - name: log-storage
          emptyDir: {}
