apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: elk-rc
  labels:
    k8s-app: elk
spec:
  template:
    metadata:
      labels:
        k8s-app: elk
    spec:
      containers:
        - image: hub.c.163.com/gobyoung/elk:elasticsearch-2
          name: elasticsearch
          ports:
            - containerPort: 9200
          volumeMounts:
            - name: es-storage
              mountPath: /usr/share/elasticsearch/data
        - image: hub.c.163.com/gobyoung/elk:logstash-2
          name: logstash
          ports:
            - containerPort: 8600
        - image: hub.c.163.com/gobyoung/elk:kibana-4
          name: kibana
          env:
            - name: ELASTICSEARCH_URL
              value: http://127.0.0.1:9200
          ports:
            - containerPort: 5601
      volumes:
        - name: es-storage
          emptyDir: {}
          #gcePersistentDisk:
          #  pdName: es-storage-v1
          #  fsType: ext4
