---
# Namespace
apiVersion: v1
kind: Namespace
metadata:
  name: elk-demo
---
# Kibana Service
apiVersion: v1
kind: Service
metadata:
  name: kibana
  namespace: elk-demo
  labels:
    k8s-app: elk
spec:
  selector:
    k8s-app: elk
  ports:
    - port: 5601
      name: kibana
---
# LogStash Service
apiVersion: v1
kind: Service
metadata:
  name: logstash
  namespace: elk-demo
  labels:
    k8s-app: elk
spec:
  selector:
    k8s-app: elk
  ports:
    - port: 8600
      name: logstash
---
# ElasticSearch Service
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  namespace: elk-demo
  labels:
    k8s-app: elk
spec:
  selector:
    k8s-app: elk
    service: elasticsearch
  ports:
    - port: 9200
      name: elasticsearch
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: elk-demo-es
  namespace: elk-demo
  labels:
    k8s-app: elk
    service: elasticsearch
spec:
  template:
    metadata:
      labels:
        k8s-app: elk
        service: elasticsearch
    spec:
      containers:
        - image: hub.c.163.com/elkdemo/elasticsearch:2.4.4-alpine
          name: elasticsearch
          ports:
            - containerPort: 9200
          volumeMounts:
            - name: es-storage
              mountPath: /usr/share/elasticsearch/data
      volumes:
        - name: es-storage
          emptyDir: {}
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: elk-demo-lk
  namespace: elk-demo
  labels:
    k8s-app: elk
    service: lk
spec:
  template:
    metadata:
      labels:
        k8s-app: elk
        service: lk
    spec:
      containers:
        - image: hub.c.163.com/elkdemo/logstash:2-alpine
          name: logstash
          ports:
            - containerPort: 8600
        - image: hub.c.163.com/elkdemo/kibana:4.1.1-alpine
          name: kibana
          env:
            - name: ELASTICSEARCH_URL
              value: http://elasticsearch:9200
          ports:
            - containerPort: 5601
      volumes:
        - name: es-storage
          emptyDir: {}
